from pathlib import Path

from src.stock_dashboard_domain_context import build_dashboard_domain_context


def test_build_dashboard_domain_context_groups_render_inputs():
    context = {
        "candidate_index": 2,
        "exp_dir": Path("/tmp/exp"),
        "daily_md_text": "daily",
        "translated_daily_md_text": "translated",
        "latest_report_text": "report",
        "health": {"score": 92},
        "health_status": "稳健",
        "health_tag": "good",
        "candidate_cards": [{"ts_code": "000001.SZ"}],
        "top1": {"ts_code": "000001.SZ"},
        "top1_signal": "strong_buy",
        "top1_risk": "low",
        "bt_diag": {"结论": "继续观察"},
        "top1_label": "000001.SZ 平安银行",
        "summary_lines": ["只读观察"],
        "update_status": {"status": "up_to_date"},
        "update_health": {"label": "ok"},
        "daily_md_href": "/daily",
        "daily_md_download_href": "/daily.md",
        "health_csv": "/tmp/health.csv",
        "health_csv_href": "/health.csv",
        "health_csv_download_href": "/health.csv?dl=1",
        "leaderboard_csv": "/tmp/leaderboard.csv",
        "leaderboard_href": "/leaderboard.csv",
        "leaderboard_download_href": "/leaderboard.csv?dl=1",
        "candidates_csv": "/tmp/candidates.csv",
        "candidates_md_href": "/candidates.md",
        "candidates_md_download_href": "/candidates.md?dl=1",
        "candidates_csv_href": "/candidates.csv",
        "candidates_csv_download_href": "/candidates.csv?dl=1",
        "latest_report_href": "/report",
        "latest_report_download_href": "/report?dl=1",
        "health_chart_html": "<div>health</div>",
        "backtest_equity_html": "<div>equity</div>",
        "backtest_drawdown_html": "<div>drawdown</div>",
        "backtest_chart_html": "<div>bt</div>",
        "backtest_map_chart_html": "<div>map</div>",
        "candidate_chart_html": "<div>candidate</div>",
        "candidate_map_chart_html": "<div>candidate-map</div>",
        "candidate_detail_html": "<div>detail</div>",
        "market_snapshot": {"dominant_regime": "震荡"},
        "basket_summary": {"expected_basket_return": 0.03},
        "basket_validation": {"summary": {}},
        "candidate_basket_feedback": {"feedback_level": "review"},
        "governance_cycle": {"previous_stable_release": {"run_id": "run-prev"}},
        "governance_cycle_state": "observe_only",
        "governance_recommended_action": "hold_observation",
        "governance_operator_message": "继续观察",
        "governance_release_readiness": {"ready_for_release": False},
        "governance_fully_release_ready": False,
        "research_batch_status": {"status": "running"},
        "daily_research_runtime": {"state": "running"},
        "effective_update_status": {"status": "up_to_date"},
        "automation_health": {"label": "ok"},
        "candidate_artifact_status": {"generated_at": "2026-04-29"},
        "prefilter_artifact_status": {"row_count": "12"},
        "research_topology": {"nodes": []},
        "grid_backtest_status": {"state": "done"},
        "evolution_status": {"latest_capacity_gate_status": "yellow"},
        "namespace_home_semantics": {
            "decision": {"headline": "primary"},
            "blocker": {"has_blocker": False},
            "execution": {"decision_action": "进入复核"},
            "evidence": {"score_gap": "12"},
            "governance": {"gate_overall_status": "通过"},
        },
        "update_timeline_panel": "<div>timeline</div>",
        "update_alerts_panel": "<div>alerts</div>",
        "backtest_scope": {"label": "近60日"},
        "report_state": "ready",
        "update_stage": "L4",
        "run_freshness": "fresh",
        "candidate_score": "95",
        "candidate_name": "平安银行",
        "candidate_count": 12,
        "candidate_source_kind": "formal",
        "candidate_source_label": "正式候选",
        "generation_mode_label": "主链结果",
        "current_basket_pointer_status": "approved",
        "current_basket_pointer_updated_at": "2026-04-29T09:00:00",
        "current_basket_pointer_basket_id": "basket-001",
        "latest_basket_attempt_status": "blocked",
        "latest_basket_attempt_generated_at": "2026-04-29T10:00:00",
        "latest_basket_attempt_blocking_reason": "gate blocked",
        "headline_tone": "继续观察",
        "headline_detail": "主结果保持锁定",
        "primary_result": {"result_id": "primary:000001.SZ"},
        "first_place_evidence_cockpit_html": "<div>cockpit</div>",
        "primary_result_card_html": "<div>primary-card</div>",
        "stock_ai_explainer": {"visible": True, "summary_text": "AI explanation"},
        "t12_minimal_facts": {"scope": "t12"},
        "t12_governance_source_facts": {"summary": "governance"},
        "primary_result_query": {"primary_conclusion": {"result_id": "primary:000001.SZ"}},
        "first_place_evidence_cockpit": {"next_check": "T+1"},
        "progress_pct_label": "80%",
    }

    domain = build_dashboard_domain_context(context)

    assert domain["core"]["candidate_index"] == 2
    assert domain["reports"]["health_csv"].name == "health.csv"
    assert domain["candidate"]["current_basket_pointer_basket_id"] == "basket-001"
    assert domain["candidate"]["candidate_source_label"] == "正式候选"
    assert domain["governance"]["previous_stable_run_id"] == "run-prev"
    assert domain["runtime"]["progress_pct_label"] == "80%"
    assert domain["primary"]["primary_result"]["result_id"] == "primary:000001.SZ"
    assert domain["primary"]["stock_ai_explainer"]["visible"] is True
    assert domain["semantics"]["execution"]["decision_action"] == "进入复核"
