#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

BASE_SHA="${GOVERNANCE_BASE_SHA:-}"
HEAD_SHA="${GOVERNANCE_HEAD_SHA:-${GITHUB_SHA:-}}"

if [[ -z "$HEAD_SHA" ]]; then
  HEAD_SHA="$(git -C "$ROOT_DIR" rev-parse HEAD)"
fi

# CI hardening defaults: always run execution-attribution hygiene dry-run.
export AIRIVO_ENABLE_EXECUTION_ATTRIBUTION_HYGIENE_GATE="${AIRIVO_ENABLE_EXECUTION_ATTRIBUTION_HYGIENE_GATE:-1}"
export AIRIVO_EXECUTION_ATTRIBUTION_HYGIENE_DB_PATH="${AIRIVO_EXECUTION_ATTRIBUTION_HYGIENE_DB_PATH:-data/openclaw.db}"
export AIRIVO_EXECUTION_ATTRIBUTION_HYGIENE_STATUSES="${AIRIVO_EXECUTION_ATTRIBUTION_HYGIENE_STATUSES:-created,submitted}"
export AIRIVO_EXECUTION_ATTRIBUTION_HYGIENE_STALE_MINUTES="${AIRIVO_EXECUTION_ATTRIBUTION_HYGIENE_STALE_MINUTES:-30}"
export AIRIVO_EXECUTION_ATTRIBUTION_HYGIENE_MAX_ORDERS="${AIRIVO_EXECUTION_ATTRIBUTION_HYGIENE_MAX_ORDERS:-500}"
export AIRIVO_EXECUTION_ATTRIBUTION_HYGIENE_AUDIT_DIR="${AIRIVO_EXECUTION_ATTRIBUTION_HYGIENE_AUDIT_DIR:-logs/openclaw}"

mkdir -p "$(dirname "$AIRIVO_EXECUTION_ATTRIBUTION_HYGIENE_DB_PATH")"
mkdir -p "$AIRIVO_EXECUTION_ATTRIBUTION_HYGIENE_AUDIT_DIR"

if [[ -n "${AIRIVO_REJECTED_BACKTEST_ARTIFACTS_FILE:-}" ]]; then
  mkdir -p "$(dirname "$AIRIVO_REJECTED_BACKTEST_ARTIFACTS_FILE")"
  touch "$AIRIVO_REJECTED_BACKTEST_ARTIFACTS_FILE"
fi

if [[ -n "$BASE_SHA" ]]; then
  exec python tools/governance_gate.py --base "$BASE_SHA" --head "$HEAD_SHA"
fi

exec python tools/governance_gate.py --all-files
