from __future__ import annotations

from pathlib import Path
from typing import Any


def build_dashboard_domain_context(context: dict[str, Any]) -> dict[str, dict[str, Any]]:
    governance_cycle = context["governance_cycle"]
    previous_stable_release = governance_cycle.get("previous_stable_release", {}) or {}
    namespace_home_semantics = context["namespace_home_semantics"]
    return {
        "core": {
            "candidate_index": int(context["candidate_index"]),
            "exp_dir": context["exp_dir"],
            "health": context["health"],
            "health_status": str(context["health_status"]),
            "health_tag": str(context["health_tag"]),
            "bt_diag": context["bt_diag"],
            "report_state": str(context["report_state"]),
            "run_freshness": str(context["run_freshness"]),
            "backtest_scope": context["backtest_scope"],
            "headline_tone": str(context["headline_tone"]),
            "headline_detail": str(context["headline_detail"]),
            "view_update_stage": str(context["update_stage"]),
            "update_status": context["update_status"],
            "update_health": context["update_health"],
        },
        "reports": {
            "daily_md_text": str(context["daily_md_text"]),
            "translated_daily_md_text": str(context["translated_daily_md_text"]),
            "latest_report_text": str(context["latest_report_text"]),
            "daily_md_href": str(context["daily_md_href"]),
            "daily_md_download_href": str(context["daily_md_download_href"]),
            "health_csv": Path(context["health_csv"]),
            "health_csv_href": str(context["health_csv_href"]),
            "health_csv_download_href": str(context["health_csv_download_href"]),
            "leaderboard_csv": Path(context["leaderboard_csv"]),
            "leaderboard_href": str(context["leaderboard_href"]),
            "leaderboard_download_href": str(context["leaderboard_download_href"]),
            "candidates_csv": Path(context["candidates_csv"]),
            "candidates_md_href": str(context["candidates_md_href"]),
            "candidates_md_download_href": str(context["candidates_md_download_href"]),
            "candidates_csv_href": str(context["candidates_csv_href"]),
            "candidates_csv_download_href": str(context["candidates_csv_download_href"]),
            "latest_report_href": str(context["latest_report_href"]),
            "latest_report_download_href": str(context["latest_report_download_href"]),
            "health_chart_html": str(context["health_chart_html"]),
            "backtest_equity_html": str(context["backtest_equity_html"]),
            "backtest_drawdown_html": str(context["backtest_drawdown_html"]),
            "backtest_chart_html": str(context["backtest_chart_html"]),
            "backtest_map_chart_html": str(context["backtest_map_chart_html"]),
            "candidate_chart_html": str(context["candidate_chart_html"]),
            "candidate_map_chart_html": str(context["candidate_map_chart_html"]),
            "candidate_detail_html": str(context["candidate_detail_html"]),
        },
        "candidate": {
            "cards": context["candidate_cards"],
            "top1": context["top1"],
            "top1_signal": str(context["top1_signal"]),
            "top1_risk": str(context["top1_risk"]),
            "top1_label": str(context["top1_label"]),
            "summary_lines": context["summary_lines"],
            "market_snapshot": context["market_snapshot"],
            "basket_summary": context["basket_summary"],
            "basket_validation": context["basket_validation"],
            "candidate_basket_feedback": context["candidate_basket_feedback"],
            "candidate_score": str(context["candidate_score"]),
            "candidate_name": str(context["candidate_name"]),
            "candidate_count": int(context["candidate_count"]),
            "candidate_source_kind": str(context.get("candidate_source_kind", "-")),
            "candidate_source_label": str(context.get("candidate_source_label", "-")),
            "generation_mode_label": str(context["generation_mode_label"]),
            "candidate_artifact_status": context["candidate_artifact_status"],
            "prefilter_artifact_status": context["prefilter_artifact_status"],
            "current_basket_pointer_status": str(context.get("current_basket_pointer_status", "-")),
            "current_basket_pointer_updated_at": str(context.get("current_basket_pointer_updated_at", "-")),
            "current_basket_pointer_basket_id": str(context.get("current_basket_pointer_basket_id", "-")),
            "latest_basket_attempt_status": str(context.get("latest_basket_attempt_status", "-")),
            "latest_basket_attempt_generated_at": str(context.get("latest_basket_attempt_generated_at", "-")),
            "latest_basket_attempt_blocking_reason": str(context.get("latest_basket_attempt_blocking_reason", "-")),
        },
        "governance": {
            "cycle": governance_cycle,
            "cycle_state": str(context["governance_cycle_state"]),
            "recommended_action": str(context["governance_recommended_action"]),
            "operator_message": str(context["governance_operator_message"]),
            "release_readiness": context["governance_release_readiness"],
            "fully_release_ready": bool(context["governance_fully_release_ready"]),
            "previous_stable_run_id": str(previous_stable_release.get("run_id", "-") or "-"),
        },
        "runtime": {
            "research_batch_status": context["research_batch_status"],
            "daily_research_runtime": context["daily_research_runtime"],
            "effective_update_status": context["effective_update_status"],
            "automation_health": context["automation_health"],
            "research_topology": context["research_topology"],
            "grid_backtest_status": context["grid_backtest_status"],
            "evolution_status": context["evolution_status"],
            "update_timeline_panel": str(context["update_timeline_panel"]),
            "update_alerts_panel": str(context["update_alerts_panel"]),
            "progress_pct_label": context["progress_pct_label"] if "progress_pct_label" in context else "-",
        },
        "primary": {
            "primary_result": context["primary_result"],
            "first_place_evidence_cockpit_section": str(context["first_place_evidence_cockpit_html"]),
            "primary_result_card_section": str(context["primary_result_card_html"]),
            "primary_result_query": context["primary_result_query"],
            "stock_ai_explainer": context.get("stock_ai_explainer", {}),
            "cockpit_model": context["first_place_evidence_cockpit"],
        },
        "t12": {
            "minimal_facts": context["t12_minimal_facts"],
            "governance_source_facts": context["t12_governance_source_facts"],
        },
        "semantics": {
            "decision": namespace_home_semantics["decision"],
            "blocker": namespace_home_semantics["blocker"],
            "execution": namespace_home_semantics["execution"],
            "evidence": namespace_home_semantics["evidence"],
            "governance": namespace_home_semantics["governance"],
        },
    }
