from __future__ import annotations

from typing import Any, Callable

from openclaw.runtime.strategy_combo_page import render_combo_strategy_page
from openclaw.runtime.strategy_v6_page import render_v6_strategy_page
from openclaw.runtime.strategy_v7_page import render_v7_strategy_page
from openclaw.runtime.strategy_v8_page import render_v8_strategy_page
from openclaw.runtime.strategy_v9_page import render_v9_strategy_page
from openclaw.runtime.today_stable_uptrend_page import render_today_stable_uptrend_page
from openclaw.runtime.today_v4_strategy_page import render_today_v4_strategy_page
from openclaw.runtime.today_v5_strategy_page import render_today_v5_strategy_page
import streamlit as st


def render_today_strategy_dispatcher(
    *,
    strategy_mode: str,
    show_ai_signal_panel: bool,
    vp_analyzer: Any,
    logger: Any,
    permanent_db_path: str,
    db_manager: Any,
    bulk_history_limit: int,
    strict_full_market_mode: bool,
    v4_evaluator_available: bool,
    v5_evaluator_available: bool,
    v6_evaluator_available: bool,
    v7_evaluator_available: bool,
    v8_evaluator_available: bool,
    stable_uptrend_available: bool,
    stable_uptrend_context_cls: type[Any],
    render_stable_uptrend_strategy: Callable[..., Any],
    load_evolve_params: Callable[[str], dict[str, Any]],
    load_strategy_center_scan_defaults: Callable[[str], tuple[dict[str, Any], str]],
    sync_scan_task_with_params: Callable[[str, dict[str, Any], str], None],
    render_scan_param_hint: Callable[[str], None],
    render_front_scan_summary: Callable[..., None],
    has_role: Callable[[str], bool],
    guard_action: Callable[[str, str, str, str], bool],
    append_action_audit: Callable[..., None],
    detect_heavy_background_job: Callable[[], tuple[bool, str]],
    start_async_scan_task: Callable[..., tuple[bool, str, str]],
    mark_scan_submitted: Callable[[str, dict[str, Any]], None],
    run_front_scan_via_offline_pipeline: Callable[..., tuple[bool, str, Any]],
    mark_front_scan_completed: Callable[..., None],
    get_db_last_trade_date: Callable[[str], str],
    load_scan_cache: Callable[..., tuple[Any, dict[str, Any]]],
    save_scan_cache: Callable[..., None],
    load_v7_cache: Callable[..., tuple[Any, dict[str, Any]]],
    save_v7_cache: Callable[..., None],
    connect_permanent_db: Callable[[], Any],
    load_candidate_stocks: Callable[..., Any],
    load_external_bonus_maps: Callable[..., Any],
    load_stock_history: Callable[..., Any],
    load_stock_history_bulk: Callable[..., Any],
    load_stock_history_fallback: Callable[..., Any],
    load_history_range_bulk: Callable[..., Any],
    batch_load_stock_histories: Callable[..., Any],
    calc_external_bonus: Callable[..., float],
    update_scan_progress_ui: Callable[..., None],
    apply_filter_mode: Callable[..., Any],
    apply_multi_period_filter: Callable[..., Any],
    add_reason_summary: Callable[..., Any],
    render_result_overview: Callable[..., None],
    render_v7_results: Callable[..., None],
    signal_density_hint: Callable[..., tuple[str, str]],
    set_stock_pool_candidate: Callable[[str, dict[str, Any], str, Any], None],
    append_reason_col: Callable[..., Any],
    standardize_result_df: Callable[..., Any],
    normalize_stock_df: Callable[..., Any],
    df_to_csv_bytes: Callable[[Any], bytes],
    render_cached_scan_results: Callable[..., None],
    render_async_scan_status: Callable[..., Any],
) -> bool:
    if "v4.0" in strategy_mode:
        render_today_v4_strategy_page(
            v4_evaluator_available=v4_evaluator_available,
            vp_analyzer=vp_analyzer,
            permanent_db_path=permanent_db_path,
            logger=logger,
            sync_scan_task_with_params=sync_scan_task_with_params,
            render_scan_param_hint=render_scan_param_hint,
            detect_heavy_background_job=detect_heavy_background_job,
            start_async_scan_task=start_async_scan_task,
            mark_scan_submitted=mark_scan_submitted,
            get_db_last_trade_date=get_db_last_trade_date,
            load_scan_cache=load_scan_cache,
            render_cached_scan_results=render_cached_scan_results,
            set_stock_pool_candidate=set_stock_pool_candidate,
            connect_permanent_db=connect_permanent_db,
            load_external_bonus_maps=load_external_bonus_maps,
            load_candidate_stocks=load_candidate_stocks,
            batch_load_stock_histories=batch_load_stock_histories,
            load_stock_history=load_stock_history,
            calc_external_bonus=calc_external_bonus,
            apply_filter_mode=apply_filter_mode,
            apply_multi_period_filter=apply_multi_period_filter,
            add_reason_summary=add_reason_summary,
            render_result_overview=render_result_overview,
            signal_density_hint=signal_density_hint,
            save_scan_cache=save_scan_cache,
            append_reason_col=append_reason_col,
            standardize_result_df=standardize_result_df,
            df_to_csv_bytes=df_to_csv_bytes,
        )
        return show_ai_signal_panel

    if "稳定上涨" in strategy_mode:
        render_today_stable_uptrend_page(
            stable_uptrend_available=stable_uptrend_available,
            permanent_db_path=permanent_db_path,
            db_manager=db_manager,
            stable_uptrend_context_cls=stable_uptrend_context_cls,
            render_stable_uptrend_strategy=render_stable_uptrend_strategy,
            df_to_csv_bytes=df_to_csv_bytes,
            render_async_scan_status=render_async_scan_status,
        )
        return show_ai_signal_panel

    if "v5.0" in strategy_mode:
        center_v5_params, center_v5_src = load_strategy_center_scan_defaults("v5")
        render_today_v5_strategy_page(
            v5_evaluator_available=v5_evaluator_available,
            vp_analyzer=vp_analyzer,
            logger=logger,
            permanent_db_path=permanent_db_path,
            strict_full_market_mode=bool(strict_full_market_mode),
            evolve_v5_core=load_evolve_params("v5_best.json"),
            center_v5_params=center_v5_params,
            center_v5_src=center_v5_src,
            airivo_has_role=has_role,
            airivo_guard_action=guard_action,
            airivo_append_action_audit=append_action_audit,
            sync_scan_task_with_params=sync_scan_task_with_params,
            render_scan_param_hint=render_scan_param_hint,
            detect_heavy_background_job=detect_heavy_background_job,
            start_async_scan_task=start_async_scan_task,
            mark_scan_submitted=mark_scan_submitted,
            get_db_last_trade_date=get_db_last_trade_date,
            load_scan_cache=load_scan_cache,
            render_cached_scan_results=render_cached_scan_results,
            set_stock_pool_candidate=set_stock_pool_candidate,
            connect_permanent_db=connect_permanent_db,
            load_candidate_stocks=load_candidate_stocks,
            load_external_bonus_maps=load_external_bonus_maps,
            load_history_range_bulk=load_history_range_bulk,
            load_stock_history=load_stock_history,
            update_scan_progress_ui=update_scan_progress_ui,
            calc_external_bonus=calc_external_bonus,
            apply_filter_mode=apply_filter_mode,
            apply_multi_period_filter=apply_multi_period_filter,
            add_reason_summary=add_reason_summary,
            signal_density_hint=signal_density_hint,
            save_scan_cache=save_scan_cache,
            append_reason_col=append_reason_col,
            standardize_result_df=standardize_result_df,
            df_to_csv_bytes=df_to_csv_bytes,
            render_async_scan_status=render_async_scan_status,
            bulk_history_limit=bulk_history_limit,
        )
        return show_ai_signal_panel

    if "v6.0" in strategy_mode:
        render_v6_strategy_page(
            vp_analyzer=vp_analyzer,
            logger=logger,
            permanent_db_path=permanent_db_path,
            v6_evaluator_available=v6_evaluator_available,
            load_evolve_params=load_evolve_params,
            sync_scan_task_with_params=sync_scan_task_with_params,
            render_scan_param_hint=render_scan_param_hint,
            detect_heavy_background_job=detect_heavy_background_job,
            start_async_scan_task=start_async_scan_task,
            mark_scan_submitted=mark_scan_submitted,
            connect_permanent_db=connect_permanent_db,
            load_candidate_stocks=load_candidate_stocks,
            load_stock_history=load_stock_history,
            load_external_bonus_maps=load_external_bonus_maps,
            calc_external_bonus=calc_external_bonus,
            update_scan_progress_ui=update_scan_progress_ui,
            apply_filter_mode=apply_filter_mode,
            apply_multi_period_filter=apply_multi_period_filter,
            add_reason_summary=add_reason_summary,
            render_result_overview=render_result_overview,
            signal_density_hint=signal_density_hint,
            set_stock_pool_candidate=set_stock_pool_candidate,
            append_reason_col=append_reason_col,
            standardize_result_df=standardize_result_df,
            df_to_csv_bytes=df_to_csv_bytes,
            render_async_scan_status=render_async_scan_status,
        )
        return show_ai_signal_panel

    if "v7.0" in strategy_mode:
        render_v7_strategy_page(
            vp_analyzer=vp_analyzer,
            logger=logger,
            permanent_db_path=permanent_db_path,
            bulk_history_limit=bulk_history_limit,
            v7_evaluator_available=v7_evaluator_available,
            load_evolve_params=load_evolve_params,
            sync_scan_task_with_params=sync_scan_task_with_params,
            render_scan_param_hint=render_scan_param_hint,
            detect_heavy_background_job=detect_heavy_background_job,
            start_async_scan_task=start_async_scan_task,
            mark_scan_submitted=mark_scan_submitted,
            get_db_last_trade_date=get_db_last_trade_date,
            load_v7_cache=load_v7_cache,
            save_v7_cache=save_v7_cache,
            connect_permanent_db=connect_permanent_db,
            load_candidate_stocks=load_candidate_stocks,
            load_external_bonus_maps=load_external_bonus_maps,
            load_stock_history_bulk=load_stock_history_bulk,
            load_stock_history=load_stock_history,
            calc_external_bonus=calc_external_bonus,
            apply_filter_mode=apply_filter_mode,
            apply_multi_period_filter=apply_multi_period_filter,
            add_reason_summary=add_reason_summary,
            render_v7_results=render_v7_results,
            set_stock_pool_candidate=set_stock_pool_candidate,
            append_reason_col=append_reason_col,
            standardize_result_df=standardize_result_df,
            df_to_csv_bytes=df_to_csv_bytes,
            render_async_scan_status=render_async_scan_status,
        )
        return show_ai_signal_panel

    if "v8.0" in strategy_mode:
        render_v8_strategy_page(
            vp_analyzer=vp_analyzer,
            logger=logger,
            permanent_db_path=permanent_db_path,
            v8_evaluator_available=v8_evaluator_available,
            strict_full_market_mode=bool(strict_full_market_mode),
            load_evolve_params=load_evolve_params,
            load_strategy_center_scan_defaults=load_strategy_center_scan_defaults,
            sync_scan_task_with_params=sync_scan_task_with_params,
            render_scan_param_hint=render_scan_param_hint,
            render_front_scan_summary=render_front_scan_summary,
            has_role=has_role,
            guard_action=guard_action,
            append_action_audit=append_action_audit,
            detect_heavy_background_job=detect_heavy_background_job,
            start_async_scan_task=start_async_scan_task,
            mark_scan_submitted=mark_scan_submitted,
            run_front_scan_via_offline_pipeline=run_front_scan_via_offline_pipeline,
            mark_front_scan_completed=mark_front_scan_completed,
            get_db_last_trade_date=get_db_last_trade_date,
            load_scan_cache=load_scan_cache,
            save_scan_cache=save_scan_cache,
            connect_permanent_db=connect_permanent_db,
            load_candidate_stocks=load_candidate_stocks,
            load_stock_history_fallback=load_stock_history_fallback,
            load_external_bonus_maps=load_external_bonus_maps,
            calc_external_bonus=calc_external_bonus,
            apply_filter_mode=apply_filter_mode,
            apply_multi_period_filter=apply_multi_period_filter,
            add_reason_summary=add_reason_summary,
            render_result_overview=render_result_overview,
            signal_density_hint=signal_density_hint,
            set_stock_pool_candidate=set_stock_pool_candidate,
            append_reason_col=append_reason_col,
            standardize_result_df=standardize_result_df,
            df_to_csv_bytes=df_to_csv_bytes,
            render_async_scan_status=render_async_scan_status,
        )
        return show_ai_signal_panel

    if "v9.0" in strategy_mode:
        render_v9_strategy_page(
            vp_analyzer=vp_analyzer,
            permanent_db_path=permanent_db_path,
            bulk_history_limit=bulk_history_limit,
            strict_full_market_mode=bool(strict_full_market_mode),
            load_evolve_params=load_evolve_params,
            load_strategy_center_scan_defaults=load_strategy_center_scan_defaults,
            has_role=has_role,
            guard_action=guard_action,
            append_action_audit=append_action_audit,
            detect_heavy_background_job=detect_heavy_background_job,
            start_async_scan_task=start_async_scan_task,
            mark_scan_submitted=mark_scan_submitted,
            sync_scan_task_with_params=sync_scan_task_with_params,
            render_scan_param_hint=render_scan_param_hint,
            get_db_last_trade_date=get_db_last_trade_date,
            load_scan_cache=load_scan_cache,
            save_scan_cache=save_scan_cache,
            connect_permanent_db=connect_permanent_db,
            load_candidate_stocks=load_candidate_stocks,
            load_external_bonus_maps=load_external_bonus_maps,
            load_history_range_bulk=load_history_range_bulk,
            apply_multi_period_filter=apply_multi_period_filter,
            add_reason_summary=add_reason_summary,
            render_result_overview=render_result_overview,
            signal_density_hint=signal_density_hint,
            set_stock_pool_candidate=set_stock_pool_candidate,
            standardize_result_df=standardize_result_df,
            df_to_csv_bytes=df_to_csv_bytes,
            update_scan_progress_ui=update_scan_progress_ui,
            render_async_scan_status=render_async_scan_status,
        )
        return show_ai_signal_panel

    if "组合策略" in strategy_mode:
        render_combo_strategy_page(
            vp_analyzer=vp_analyzer,
            permanent_db_path=permanent_db_path,
            bulk_history_limit=bulk_history_limit,
            strict_full_market_mode=bool(strict_full_market_mode),
            load_evolve_params=load_evolve_params,
            load_strategy_center_scan_defaults=load_strategy_center_scan_defaults,
            has_role=has_role,
            guard_action=guard_action,
            append_action_audit=append_action_audit,
            detect_heavy_background_job=detect_heavy_background_job,
            start_async_scan_task=start_async_scan_task,
            mark_scan_submitted=mark_scan_submitted,
            run_front_scan_via_offline_pipeline=run_front_scan_via_offline_pipeline,
            mark_front_scan_completed=mark_front_scan_completed,
            get_db_last_trade_date=get_db_last_trade_date,
            load_scan_cache=load_scan_cache,
            save_scan_cache=save_scan_cache,
            connect_permanent_db=connect_permanent_db,
            load_candidate_stocks=load_candidate_stocks,
            load_external_bonus_maps=load_external_bonus_maps,
            load_history_range_bulk=load_history_range_bulk,
            normalize_stock_df=normalize_stock_df,
            sync_scan_task_with_params=sync_scan_task_with_params,
            render_scan_param_hint=render_scan_param_hint,
            render_front_scan_summary=render_front_scan_summary,
            apply_multi_period_filter=apply_multi_period_filter,
            add_reason_summary=add_reason_summary,
            render_result_overview=render_result_overview,
            signal_density_hint=signal_density_hint,
            set_stock_pool_candidate=set_stock_pool_candidate,
            standardize_result_df=standardize_result_df,
            df_to_csv_bytes=df_to_csv_bytes,
            update_scan_progress_ui=update_scan_progress_ui,
            render_async_scan_status=render_async_scan_status,
            calc_external_bonus=calc_external_bonus,
        )
        return show_ai_signal_panel

    if "AI 辅助选股" in strategy_mode:
        st.info("已切换至实验策略：AI 辅助选股。下方将显示 AI 智能选股面板。")
        return True

    st.info("该策略不在核心生产区。请在“实验策略入口（手动启用）”中选择 v4/v6/v7/stable/ai。")
    st.stop()
    return show_ai_signal_panel
