import argparse
import json
from datetime import datetime
from pathlib import Path

from src.utils.project_paths import resolve_project_path


def _read_json(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


def _to_int(value: object, default: int) -> int:
    try:
        return int(value)
    except Exception:
        return int(default)


def _build_markdown(payload: dict) -> str:
    lines = [
        "# T12 Threshold Autotune Report",
        "",
        f"Generated at: {payload.get('generated_at', '')}",
        f"Applied: `{payload.get('applied', False)}`",
        f"Reason: {payload.get('reason', '')}",
        "",
        "## Thresholds",
        f"- Before: warn/fail/fail_streak = {payload.get('before', {}).get('warn_hot_threshold', '-')}/"
        f"{payload.get('before', {}).get('fail_hot_threshold', '-')}/"
        f"{payload.get('before', {}).get('fail_streak_hot_threshold', '-')}",
        f"- After:  warn/fail/fail_streak = {payload.get('after', {}).get('warn_hot_threshold', '-')}/"
        f"{payload.get('after', {}).get('fail_hot_threshold', '-')}/"
        f"{payload.get('after', {}).get('fail_streak_hot_threshold', '-')}",
        "",
        "## Safety Gate",
        f"- recommendation: {payload.get('recommendation', 'unknown')}",
        f"- recent_runs: {payload.get('recent_runs', 0)}",
        f"- pass/warn/fail: {payload.get('pass_runs', 0)}/{payload.get('warn_runs', 0)}/{payload.get('fail_runs', 0)}",
        f"- min_recent_runs: {payload.get('min_recent_runs', 0)}",
        "",
        "## Rollback Guard",
        f"- triggered/applied: {payload.get('rollback', {}).get('triggered', False)}/"
        f"{payload.get('rollback', {}).get('applied', False)}",
        f"- reason: {payload.get('rollback', {}).get('reason', '')}",
        f"- rollback_event_count: {payload.get('rollback', {}).get('event_count', 0)}",
        "",
    ]
    return "\n".join(lines)


def _write_env(path: Path, warn: int, fail: int, fail_streak: int) -> None:
    lines = [
        "# Auto-generated by run_t12_threshold_autotune.py",
        f"# generated_at={datetime.now().isoformat()}",
        f"T12_ALERT_WARN_HOT_THRESHOLD={warn}",
        f"T12_ALERT_FAIL_HOT_THRESHOLD={fail}",
        f"T12_ALERT_FAIL_STREAK_HOT_THRESHOLD={fail_streak}",
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Safely apply adaptive thresholds to onsite T12 control env")
    parser.add_argument("--output-dir", default="data/experiments")
    parser.add_argument("--control-env-file", default="data/experiments/t12_thresholds.env")
    parser.add_argument("--min-recent-runs", type=int, default=5)
    parser.add_argument("--max-threshold", type=int, default=5)
    parser.add_argument("--min-threshold", type=int, default=1)
    parser.add_argument("--stable-snapshot-file", default="data/experiments/t12_threshold_stable_snapshot.json")
    parser.add_argument("--rollback-events-file", default="data/experiments/t12_threshold_rollback_events.json")
    parser.add_argument("--rollback-warn-runs", type=int, default=3)
    parser.add_argument("--rollback-fail-runs", type=int, default=1)
    parser.add_argument("--rollback-fail-streak", type=int, default=1)
    args = parser.parse_args()

    out_dir = resolve_project_path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    control_env_file = Path(args.control_env_file)
    if not control_env_file.is_absolute():
        control_env_file = resolve_project_path(str(control_env_file))
    stable_snapshot_file = Path(args.stable_snapshot_file)
    if not stable_snapshot_file.is_absolute():
        stable_snapshot_file = resolve_project_path(str(stable_snapshot_file))
    rollback_events_file = Path(args.rollback_events_file)
    if not rollback_events_file.is_absolute():
        rollback_events_file = resolve_project_path(str(rollback_events_file))

    alert = _read_json(out_dir / "t12_alert_center_latest.json")
    adaptive = (alert or {}).get("adaptive_thresholds", {}) or {}
    trend = (alert or {}).get("trend", {}) or {}

    current_warn = _to_int(adaptive.get("current_warn_hot_threshold"), 2)
    current_fail = _to_int(adaptive.get("current_fail_hot_threshold"), 2)
    current_streak = _to_int(adaptive.get("current_fail_streak_hot_threshold"), 1)
    suggested_warn = _to_int(adaptive.get("suggested_warn_hot_threshold"), current_warn)
    suggested_fail = _to_int(adaptive.get("suggested_fail_hot_threshold"), current_fail)
    suggested_streak = _to_int(adaptive.get("suggested_fail_streak_hot_threshold"), current_streak)
    recommendation = str(adaptive.get("recommendation", "keep_current")).strip().lower()

    recent_runs = _to_int(trend.get("recent_runs"), 0)
    pass_runs = _to_int(trend.get("pass_runs"), 0)
    warn_runs = _to_int(trend.get("warn_runs"), 0)
    fail_runs = _to_int(trend.get("fail_runs"), 0)
    recent_fail_streak = _to_int(trend.get("recent_fail_streak"), 0)

    min_recent_runs = max(int(args.min_recent_runs), 3)
    min_threshold = max(int(args.min_threshold), 1)
    max_threshold = max(int(args.max_threshold), min_threshold)

    applied = False
    reason = "keep current thresholds"
    next_warn, next_fail, next_streak = current_warn, current_fail, current_streak

    if recommendation == "tighten_thresholds":
        if recent_runs >= min_recent_runs and warn_runs == 0 and fail_runs == 0:
            next_warn = max(min(suggested_warn, max_threshold), min_threshold)
            next_fail = max(min(suggested_fail, max_threshold), min_threshold)
            next_streak = max(min(suggested_streak, max_threshold), min_threshold)
            applied = (next_warn, next_fail, next_streak) != (current_warn, current_fail, current_streak)
            reason = "tighten applied under stable pass regime" if applied else "tighten suggested but unchanged"
        else:
            reason = "tighten rejected by safety gate (insufficient stable pass history)"
    elif recommendation in {"relax_warn_thresholds", "relax_fail_thresholds"}:
        if fail_runs > 0 or warn_runs >= 2:
            next_warn = max(min(suggested_warn, max_threshold), min_threshold)
            next_fail = max(min(suggested_fail, max_threshold), min_threshold)
            next_streak = max(min(suggested_streak, max_threshold), min_threshold)
            applied = (next_warn, next_fail, next_streak) != (current_warn, current_fail, current_streak)
            reason = "relax applied under elevated warning/failure regime" if applied else "relax suggested but unchanged"
        else:
            reason = "relax rejected by safety gate (no warning/failure pressure)"
    else:
        reason = "recommendation is keep_current"

    rollback_warn_runs = max(_to_int(args.rollback_warn_runs, 3), 1)
    rollback_fail_runs = max(_to_int(args.rollback_fail_runs, 1), 1)
    rollback_fail_streak = max(_to_int(args.rollback_fail_streak, 1), 1)
    rollback_triggered = (
        warn_runs >= rollback_warn_runs
        or fail_runs >= rollback_fail_runs
        or recent_fail_streak >= rollback_fail_streak
    )
    rollback_applied = False
    rollback_reason = "not triggered"
    rollback_events_raw = _read_json(rollback_events_file).get("items", [])
    rollback_events = rollback_events_raw if isinstance(rollback_events_raw, list) else []
    stable_snapshot = _read_json(stable_snapshot_file)
    stable_thresholds = (stable_snapshot or {}).get("thresholds", {}) or {}
    stable_warn = _to_int(stable_thresholds.get("warn_hot_threshold"), current_warn)
    stable_fail = _to_int(stable_thresholds.get("fail_hot_threshold"), current_fail)
    stable_streak = _to_int(stable_thresholds.get("fail_streak_hot_threshold"), current_streak)

    if rollback_triggered:
        has_snapshot = isinstance(stable_thresholds, dict) and bool(stable_thresholds)
        if has_snapshot:
            before_tuple = (next_warn, next_fail, next_streak)
            next_warn, next_fail, next_streak = stable_warn, stable_fail, stable_streak
            rollback_applied = before_tuple != (next_warn, next_fail, next_streak)
            if rollback_applied:
                rollback_reason = "rollback to stable snapshot thresholds due to warning/failure pressure"
                rollback_events.append(
                    {
                        "generated_at": datetime.now().isoformat(),
                        "trigger": {
                            "warn_runs": warn_runs,
                            "fail_runs": fail_runs,
                            "recent_fail_streak": recent_fail_streak,
                            "rollback_warn_runs": rollback_warn_runs,
                            "rollback_fail_runs": rollback_fail_runs,
                            "rollback_fail_streak": rollback_fail_streak,
                        },
                        "from": {
                            "warn_hot_threshold": before_tuple[0],
                            "fail_hot_threshold": before_tuple[1],
                            "fail_streak_hot_threshold": before_tuple[2],
                        },
                        "to": {
                            "warn_hot_threshold": next_warn,
                            "fail_hot_threshold": next_fail,
                            "fail_streak_hot_threshold": next_streak,
                        },
                    }
                )
            else:
                rollback_reason = "triggered but already on stable snapshot thresholds"
        else:
            rollback_reason = "triggered but stable snapshot is missing"
    rollback_events = rollback_events[-100:]

    _write_env(control_env_file, next_warn, next_fail, next_streak)

    if not rollback_triggered and warn_runs == 0 and fail_runs == 0:
        stable_snapshot_file.parent.mkdir(parents=True, exist_ok=True)
        stable_snapshot_file.write_text(
            json.dumps(
                {
                    "generated_at": datetime.now().isoformat(),
                    "thresholds": {
                        "warn_hot_threshold": next_warn,
                        "fail_hot_threshold": next_fail,
                        "fail_streak_hot_threshold": next_streak,
                    },
                },
                ensure_ascii=False,
                indent=2,
            ),
            encoding="utf-8",
        )
    rollback_events_file.parent.mkdir(parents=True, exist_ok=True)
    rollback_events_file.write_text(json.dumps({"items": rollback_events}, ensure_ascii=False, indent=2), encoding="utf-8")

    payload = {
        "generated_at": datetime.now().isoformat(),
        "applied": applied,
        "reason": reason,
        "recommendation": recommendation,
        "recent_runs": recent_runs,
        "pass_runs": pass_runs,
        "warn_runs": warn_runs,
        "fail_runs": fail_runs,
        "min_recent_runs": min_recent_runs,
        "control_env_file": str(control_env_file),
        "stable_snapshot_file": str(stable_snapshot_file),
        "rollback_events_file": str(rollback_events_file),
        "before": {
            "warn_hot_threshold": current_warn,
            "fail_hot_threshold": current_fail,
            "fail_streak_hot_threshold": current_streak,
        },
        "after": {
            "warn_hot_threshold": next_warn,
            "fail_hot_threshold": next_fail,
            "fail_streak_hot_threshold": next_streak,
        },
        "rollback": {
            "triggered": rollback_triggered,
            "applied": rollback_applied,
            "reason": rollback_reason,
            "event_count": len(rollback_events),
        },
    }

    out_json = out_dir / "t12_threshold_control_latest.json"
    out_md = out_dir / "t12_threshold_control_latest.md"
    out_json.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    out_md.write_text(_build_markdown(payload), encoding="utf-8")
    print(str(out_json))
    print(str(out_md))
    print(str(control_env_file))
    print(str(stable_snapshot_file))
    print(str(rollback_events_file))


if __name__ == "__main__":
    main()
